function spotStats = appendCase13SpotStats( ...
    spotStats, pa_total, x_range, y_range, z_range, ...
    xframe, yframe, frame_idx, static_Nframe, ...
    center_x_new, center_y_new, center_z_new)

spot_id = spotStats.next_spot_id;
spotStats.next_spot_id = spot_id + 1;

[idx_center, coord_center, peak_intensity_center] = detectParticleCenter3D( ...
    pa_total, x_range, y_range, z_range);
idx_center_y = idx_center(1);
idx_center_x = idx_center(2);
idx_center_z = idx_center(3);
center_x_detected = coord_center(1);
center_y_detected = coord_center(2);
center_z_detected = coord_center(3);

profile_x = double(squeeze(pa_total(idx_center_y, :, idx_center_z)));
profile_y = double(squeeze(pa_total(:, idx_center_x, idx_center_z)));
profile_z = double(squeeze(pa_total(idx_center_y, idx_center_x, :)));
profile_x = profile_x(:);
profile_y = profile_y(:);
profile_z = profile_z(:);

coord_x = double(x_range(:));
coord_y = double(y_range(:));
coord_z = double(z_range(:));

[fwhm_x, peak_x] = computeProfileFWHM(coord_x, profile_x);
[fwhm_y, peak_y] = computeProfileFWHM(coord_y, profile_y);
[fwhm_z, peak_z] = computeProfileFWHM(coord_z, profile_z);

spotSummaryRow = struct( ...
    'spot_id', spot_id, ...
    'xframe', xframe, ...
    'yframe', yframe, ...
    'frame_idx', frame_idx, ...
    'static_Nframe', static_Nframe, ...
    'center_x_new', center_x_new, ...
    'center_y_new', center_y_new, ...
    'center_z_new', center_z_new, ...
    'center_x_detected', center_x_detected, ...
    'center_y_detected', center_y_detected, ...
    'center_z_detected', center_z_detected, ...
    'center_dx', center_x_detected - center_x_new, ...
    'center_dy', center_y_detected - center_y_new, ...
    'center_dz', center_z_detected - center_z_new, ...
    'peak_intensity_center', peak_intensity_center, ...
    'peak_x', peak_x, ...
    'peak_y', peak_y, ...
    'peak_z', peak_z, ...
    'fwhm_x', fwhm_x, ...
    'fwhm_y', fwhm_y, ...
    'fwhm_z', fwhm_z);
spotStats.summary(end + 1, 1) = spotSummaryRow;

spotStats.profiles = [ ...
    spotStats.profiles; ...
    createAxisRows(spot_id, xframe, yframe, 'x', coord_x, profile_x, coord_center); ...
    createAxisRows(spot_id, xframe, yframe, 'y', coord_y, profile_y, coord_center); ...
    createAxisRows(spot_id, xframe, yframe, 'z', coord_z, profile_z, coord_center)];
end

function rows = createAxisRows(spot_id, xframe, yframe, axis_name, coord, intensity, coord_center)
n = numel(coord);
rows = repmat(struct( ...
    'spot_id', [], ...
    'xframe', [], ...
    'yframe', [], ...
    'axis_name', '', ...
    'sample_index', [], ...
    'coord', [], ...
    'intensity', [], ...
    'center_x_detected', [], ...
    'center_y_detected', [], ...
    'center_z_detected', [], ...
    'center_type', ''), n, 1);

for k = 1:n
    rows(k) = struct( ...
        'spot_id', spot_id, ...
        'xframe', xframe, ...
        'yframe', yframe, ...
        'axis_name', axis_name, ...
        'sample_index', k, ...
        'coord', coord(k), ...
        'intensity', intensity(k), ...
        'center_x_detected', coord_center(1), ...
        'center_y_detected', coord_center(2), ...
        'center_z_detected', coord_center(3), ...
        'center_type', 'detected_peak');
end
end
