function spotStats = initCase13SpotStats()
spotStats = struct();
spotStats.next_spot_id = 1;
spotStats.summary = repmat(struct( ...
    'spot_id', [], ...
    'xframe', [], ...
    'yframe', [], ...
    'frame_idx', [], ...
    'static_Nframe', [], ...
    'center_x_new', [], ...
    'center_y_new', [], ...
    'center_z_new', [], ...
    'center_x_detected', [], ...
    'center_y_detected', [], ...
    'center_z_detected', [], ...
    'center_dx', [], ...
    'center_dy', [], ...
    'center_dz', [], ...
    'peak_intensity_center', [], ...
    'peak_x', [], ...
    'peak_y', [], ...
    'peak_z', [], ...
    'fwhm_x', [], ...
    'fwhm_y', [], ...
    'fwhm_z', []), 0, 1);
spotStats.profiles = repmat(struct( ...
    'spot_id', [], ...
    'xframe', [], ...
    'yframe', [], ...
    'axis_name', '', ...
    'sample_index', [], ...
    'coord', [], ...
    'intensity', [], ...
    'center_x_detected', [], ...
    'center_y_detected', [], ...
    'center_z_detected', [], ...
    'center_type', ''), 0, 1);
end
